name: Check Code
permissions:
  contents: read
  pull-requests: read

on: [push, pull_request, workflow_dispatch]

jobs:
  
  tests:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python-version: [3.11.1]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}


      - name: Install depedencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Copy env
        run: cp .env.example .env
          
      - name: Run tests
        run: |
          cd src
          Python manage.py test

      - name: Relat√≥rio de cobertura de testes
        run: |
          cd src
          coverage run manage.py test
          coverage report
          coverage html -d htmlcov --omit='.venv/*'